const ru = {
  login:"Логин",
  password:"Пароль",
  login_button:"Войти",
  login_title:"Войдите в свою учетную запись",
  summa:"Сумма",
  sum:"Сум",
  pcs:"шт",
  cancel:"Отмена",
  read:"Читать",
  ok:"Ок",
  save:"Сохранить",
  client:"Клиент",
  choose:"Выбрать",
  middleName:"Отчество",
  add_goods:"Добавить товар",
  passportFormat:"Формат серии паспорта: AA1234567",
  pinflFormat:"ПНФЛ должен содержать 14 цифр",
  innFormat:"INN должен содержать от 9 до 14 цифр",
  percentFormat:"Enter a valid percentage (0-100)",
  monthFormat:"Enter a valid number of months",
  phoneFormat:"Номер телефона должен быть в формате +998XXXXXXXXX",
  please_enter:(name:string)=> `Пожалуйста, введите  ${name}`,
  paginationData:(from:string, to:string, total:string) => `Показ от ${from} до ${to} из ${total} элементов`,
  paginationData2:(from:string, total:string) => `Показано ${from} из ${total} результатов`,

  addClient:"Добавить клиента",
  editClient:"Редактировать клиента",
  passport_given_by:"Паспорт выдан",
  pleaseChoose:"Пожалуйста, выберите клиента",
  open_table:"Открыть таблицу",
  close:"Закрыть",
  profile:"Профиль",
  logout:"Выход",
  month:"Месяц",
  passport_expire_date:"Срок действия паспорта",
  personal_info:"Личные данные",
payment_history:"История платежей",
company_name:"Название компании",
created_at:"Дата создания",
manager:"Менеджер",
entre_input:(name:string) => `Введите ${name}`,
owner:"Руководитель",
admin:`Администратор магазина`,
responsble_person:"Ответственное лицо",
extra_phone:" Дополнительный номер телефона",
pay_date:"Дата оплаты",
  create:"Создать",
  search:"Поиск",
  home:"Главная",
  payment:"Оплата",
  percent:"Процент",
  inital_cost:"Начальная цена",
  total_cost:"Общая цена",
  total_months:"Всего месяцев",
  firstName:"Имя",
  name:"Название",
  lastName:"Фамилия",
  products:"Продукты",
  list:"Список",
  quantity:"Количество",
  price:"Цена",
  unit:"Единица",
  client_info:"Информация о клиенте",
  monthlyFee:"Ежемесячный платеж",
  payment_type:"Способ оплаты",
  contractInner:"Детали договора",
  description:"Описание",
    fullName: "Полное имя",
    passportSeries: "Серия паспорта",
    pinfl: "ПНФЛ",
    passportExpiryDate: "Срок действия паспорта",
    birthday: "Дата рождения",
    phone: "Телефон",
    address: "Адрес",
    rating: "Рейтинг",
    edit: "Редактировать",
    view: "Просмотр",
    status:"Статус",
    actions: "Действия",
    clients: "Клиенты",
    contracts: "Договоры",
    genisis_contracts:"Договоры Genesis",
    genesisContracts: "Генезис контракты",
    notifications: "Уведомления",
      "title": "Контракты",
inn: "ИНН",
id: "ID",
      "contract_number": "№ контракта",
      date: "Дата",
      paidMonth: "Оплаченный месяц",
      unpaidMonth: "Неоплаченный месяц",
      unpaid: "Неоплачено",
      fee: "Пошлина",
      payed: "Оплачено",
      fromDate: "Дата начала",
    toDate:"Дата окончания",
    total:"Всего",
  }

  export default ru;