const uz = {
  login: "Login",
  password: "Parol",
 login_button:"Kirish",
 login_title:"Hisobingizga kirish",
  summa: "Summasi",
  sum: "So'm",
  pcs: "dona",
  cancel: "Bekor qilish",
  read: "O'qish",
  ok: "Ok",
  save: "Saqlash",
  client: "Mijoz",
  choose: "Tanlash",
  middleName: "Otasining ismi",
  add_goods: "Mahsulot qo'shish",
  passportFormat: "Pasport seriyasi formati: AA1234567",
  pinflFormat: "PINFL 14 raqamdan iborat bo'lishi kerak",
  innFormat: "INN 9 dan 14 gacha raqamdan iborat bo'lishi kerak",
  percentFormat: "Yaroqli foizni kiriting (0-100)",
  monthFormat: "Yaroqli oy sonini kiriting",
  phoneFormat: "Telefon raqami formati: +998XXXXXXXXX",
  please_enter: (name: string) => `Iltimos, ${name} kiriting`,
  paginationData: (from: string, to: string, total: string) => `Ko'rsatilmoqda ${from} dan ${to} gacha, jami ${total} ta element`,
  paginationData2: (from: string, total: string) => `Ko'rsatilgan: ${from} dan jami ${total} ta natija`,

  addClient: "Mijoz qo'shish",
  editClient: "Mijozni tahrirlash",
  passport_given_by: "Pasport bergan tashkilot",
  pleaseChoose: "Iltimos, mijozni tanlang",
  open_table: "Jadvalni ochish",
  close: "Yopish",
  profile: "Profil",
  logout: "Chiqish",
  month: "Oy",
  passport_expire_date: "Pasport amal qilish muddati",
  personal_info: "Shaxsiy ma'lumotlar",
  payment_history: "To'lovlar tarixi",
  company_name: "Kompaniya nomi",
  created_at: "Yaratilgan sana",
  manager: "Menejer",
  entre_input: (name: string) => `${name}ni kiriting`,
  owner: "Rahbar",
  admin: "Do'kon administratori",
  responsble_person: "Mas'ul shaxs",
  extra_phone: "Qo'shimcha telefon raqami",
  pay_date: "To'lov sanasi",
  create: "Yaratish",
  search: "Qidiruv",
  home: "Bosh sahifa",
  payment: "To'lov",
  percent: "Foiz",
  inital_cost: "Boshlang'ich narx",
  total_cost: "Umumiy narx",
  total_months: "Jami oylar",
  firstName: "Ismi",
  name: "Nomi",
  lastName: "Familiyasi",
  products: "Mahsulotlar",
  list: "Ro'yxat",
  quantity: "Miqdor",
  price: "Narxi",
  unit: "Birlik",
  client_info: "Mijoz haqida ma'lumot",
  monthlyFee: "Oylik to'lov",
  payment_type: "To'lov turi",
  contractInner: "Shartnoma tafsilotlari",
  description: "Tavsif",
  fullName: "To'liq ismi",
  passportSeries: "Pasport seriyasi",
  pinfl: "PINFL",
  passportExpiryDate: "Pasport amal qilish muddati",
  birthday: "Tug'ilgan sana",
  phone: "Telefon",
  address: "Manzil",
  rating: "Reyting",
  edit: "Tahrirlash",
  view: "Ko'rish",
  status: "Holat",
  actions: "Harakatlar",
  clients: "Mijozlar",
  contracts: "Shartnomalar",
  genisis_contracts: "Genesis shartnomalari",
  genesisContracts: "Genesis shartnomalari",
  notifications: "Bildirishnomalar",
  title: "Shartnomalar",
  inn: "STIR",
  id: "ID",
  contract_number: "Shartnoma raqami",
  date: "Sana",
  paidMonth: "To'langan oy",
  unpaidMonth: "To'lanmagan oy",
  unpaid: "To'lanmagan",
  fee: "To'lov",
  payed: "To'langan",
  fromDate: "Boshlanish sanasi",
  toDate: "Tugash sanasi",
  total: "Jami",
};

export default uz;
